language: scala
env:
  - ISABELLE_HOME=./contrib/Isabelle2014
before_install:
  - mkdir -p contrib
  - curl -s http://www21.in.tum.de/~hupel/libisabelle/Isabelle2014_HOL_linux_x86-64.tar.gz | tar xzf - -C contrib
install:
  - "$ISABELLE_HOME"/bin/isabelle build -d . -bv Hello_PIDE
script:
  - sbt test:compile
  - sbt test
